### ISSUE TITLE
Query params don't support nested maps

### ISSUE THREAD

**Issue by vincentjames501** [RutledgePaulV/clj-okhttp#12]
It would be nice if `:query-params` supported nested maps such as clj-http:

```clojure
;; "Nested" query parameters
;; (this yields a query string of `a[e][f]=6&a[b][c]=5`)
(client/get "http://example.com/search" {:query-params {:a {:b {:c 5} :e {:f 6}}}})
```

It does support vectors nicely!

**Comment by RutledgePaulV** [comment]
I'm open to support for this given an efficient implementation

**Comment by vincentjames501** [comment]
@RutledgePaulV , we'd probably have to abandon using OkHttpClient's addQueryParamter function and just set the query directly from my quick research. I may take a crack at it.

**Comment by RutledgePaulV** [comment]
Fixed in https://github.com/RutledgePaulV/clj-okhttp/pull/19
