### ISSUE TITLE
Consider supporting `:content-type` and `:accept` request keys

### ISSUE THREAD

**Issue by vincentjames501** [RutledgePaulV/clj-okhttp#13]
This could help with automatic coercion of `:body` params for example similar to what `clj-http` does when submitting something like `:content-type :json`

**Comment by RutledgePaulV** [comment]
clj-okhttp considers the "Content-Type" header of the request when encoding the body. I think it's a mistake to support the option in two different places (though I realize it would provide better compatibility with clj-http). Similarly, if you want to set an accept header, why not just set a "Accept" header.

**Comment by vincentjames501** [comment]
@RutledgePaulV , I think that's fair and I agree (though it's a bit more painful to type):

```clojure
(http/post "feh" {:content-type :json :accept :json :body {}})
```

vs

```clojure
(http/post "feh" {:headers {"content-type" "application/json; charset=utf-8;" 
                                            "accept" "application/json; charset=utf-8;" 
                            :body {}})
```


 I'll close this.
