### ISSUE TITLE
Thoughts on per-request client options?

### ISSUE THREAD

**Issue by vincentjames501** [RutledgePaulV/clj-okhttp#15]
Right now you're allowed to override some behavior such as middleware on a per-request basis. What are your thoughts on allowing it for certain client options like :read-timeout, :write-timeouts, etc? I can see an argument both for and against:

For

* It's more inline with other http clients
* It's convenient for one-off requests
* It may be a bit more natural and allow passing data/configuration through your system a bit easier

Against

* It's different than the model that OkHttpClient uses.
* It's not that hard to just do new-client reusing your existing one.

Even if we don't support top-level keys like `:read-timeout`, `:write-timeout`, etc on the request, it could be nice to supply something like:

```clojure
(http/get client "https://google.com" {:client-options {:read-timeout 1000}})
```

**Comment by RutledgePaulV** [comment]
Yeah, there's a 2 arity version of `create-client` that supports cloning an existing client + passing a map of altered options. I think that's the only interface I want to provide for this.

**Comment by RutledgePaulV** [comment]
Sorry, but I'm not going to support this because I think it's important to manage your connection pools / client instances and providing an interface like this would be hiding a temporary http client. The tools are there to create this functionality in your app if desired.

```clojure
(defn request-with-client-opts [client request]
   (if (contains? request :client-options)
       (http/request (http/create-client client (:client-options request)) request)
       (http/request client request)))
```
